name: Automerge

on:
  pull_request:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changes
        id: git_diff
        uses: technote-space/get-diff-action@v5
        with:
          FILES: |
            src/tokens/solana.tokenlist.json

      - uses: reitermarkus/automerge@v1.5.2
        if: steps.git_diff.outputs.insertions == 0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge

      - run: Deleted files
        if: steps.git_diff.outputs.insertions > 0
        run: echo "Deleted ${{ steps.git_diff.outputs.insertions }} lines."
