name: Automerge

on:
  pull_request_target:
  push:
    branches:
      - main
    types:
      - opened
      - synchronized
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changes
        id: git_diff
        uses: swmd/get-pr-diff@v0.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge pull request
        if: ${{ steps.git_diff.outputs.valid == 'VALID' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
