name: Automerge

on:
  schedule:
    - cron: 0 * * * *
  pull_request_target:
  push:
    branches:
      - main
    types:
      - opened
      - synchronized
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changes
        id: git_diff
        uses: swmd/get-diff-action@v5.0.2
        with:
          FILES: |
            src/tokens/solana.tokenlist.json

      - name: Merge pull request
        if: steps.git_diff.outputs.deletions == 0
        uses: reitermarkus/automerge@v1.5.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: rebase
          do-not-merge-labels: never-merge
