name: Automerge

on:
  pull_request:
    branches: [ main ]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: git checkout auto-merge

      - name: Get changes
        id: git-diff
        uses: technote-space/get-diff-action@v5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES: |
            src/tokens/solana.tokenlist.json
          FORMAT: json

      - run: echo '${{ env.GIT_DIFF }}' | jq .

      # - uses: reitermarkus/automerge@v1.5.2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     merge-method: rebase
      #     do-not-merge-labels: never-merge
