name: Automerge

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get changes
        id: git_diff
        uses: technote-space/get-diff-action@v5
        with:
          FILES: |
            src/tokens/solana.tokenlist.json
          FORMAT: json

      - run: echo ${{ steps.git_diff.outputs.insertions }} | jq .

      # - uses: reitermarkus/automerge@v1.5.2
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     merge-method: rebase
      #     do-not-merge-labels: never-merge
